apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter-deployment
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: blackbox-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:v0.19.0
          ports:
            - containerPort: 9115

---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter-service
  namespace: monitoring
spec:
  selector:
    app: blackbox-exporter
  type: NodePort
  ports:
    - protocol: TCP
      port: 9115
      targetPort: 9115